import React from 'react';
import { PrintData } from '../types';

interface PrintableResultProps {
  data: PrintData;
}

const PrintableResult: React.FC<PrintableResultProps> = ({ data }) => {
  return (
    <div id="print-container" className="p-12 font-sans text-gray-900 bg-white hidden print:block overflow-visible min-h-screen">
      <header className="flex justify-between items-start pb-8 border-b-2 border-gray-100 mb-8">
        <div className="space-y-1">
          <h1 className="text-3xl font-black tracking-tighter text-gray-900">
            COMPLIANCE <span className="text-blue-600">REPORT</span>
          </h1>
          <p className="text-[10px] font-bold uppercase tracking-widest text-gray-400">
            Generated by TEU GLOBAL AI Intelligence Cluster
          </p>
        </div>
        <div className="text-right">
           <h2 className="text-lg font-black text-orange-600">TRADE EXPEDITORS INC.</h2>
           <p className="text-xs font-bold text-gray-500">DBA TEU GLOBAL</p>
           <p className="text-[10px] text-gray-400 mt-2">Date: {new Date().toLocaleDateString()}</p>
           <p className="text-[10px] text-gray-400">Reference: #{Math.random().toString(36).substr(2, 9).toUpperCase()}</p>
        </div>
      </header>

      <main className="space-y-10">
        {/* Summary Header */}
        <div className="bg-gray-50 p-6 rounded-2xl border border-gray-100">
           <h3 className="text-[10px] font-black uppercase tracking-widest text-gray-400 mb-4">Executive Summary</h3>
           <div className="grid grid-cols-2 gap-8">
              <div>
                 <p className="text-[10px] font-bold text-gray-500 uppercase mb-1">Recommended HTS Code</p>
                 <p className="text-2xl font-black text-blue-700 font-mono tracking-tighter">{data.htsCode}</p>
              </div>
              <div>
                 <p className="text-[10px] font-bold text-gray-500 uppercase mb-1">Total Estimated Duty</p>
                 <p className="text-2xl font-black text-emerald-600 tracking-tighter">{data.dutyInfo.general}</p>
              </div>
           </div>
        </div>

        {/* Query Context */}
        <section>
          <h4 className="text-[10px] font-black uppercase tracking-[0.2em] text-gray-400 mb-3 border-b border-gray-100 pb-1">Input Context</h4>
          <p className="text-sm font-bold text-gray-700 leading-relaxed italic">"{data.query}"</p>
        </section>

        {/* Detailed Data Tables */}
        <section className="space-y-6">
           <h4 className="text-[10px] font-black uppercase tracking-[0.2em] text-gray-400 mb-3 border-b border-gray-100 pb-1">Classification Details</h4>
           
           <div className="overflow-hidden rounded-xl border border-gray-200">
              <table className="w-full text-left text-xs border-collapse">
                <thead>
                   <tr className="bg-gray-50">
                      <th className="p-4 font-black uppercase tracking-widest text-gray-500 border-b border-gray-200">Target Scenario</th>
                      <th className="p-4 font-black uppercase tracking-widest text-gray-500 border-b border-gray-200">HTS Description</th>
                   </tr>
                </thead>
                <tbody>
                   <tr>
                      <td className="p-4 font-bold text-gray-900 border-r border-gray-200 w-1/3 align-top">{data.scenarioDescription}</td>
                      <td className="p-4 text-gray-600 leading-relaxed align-top">Refer to Section Notes and General Rules of Interpretation (GRI) included in full report.</td>
                   </tr>
                </tbody>
              </table>
           </div>

           <div className="overflow-hidden rounded-xl border border-gray-200">
              <table className="w-full text-left text-xs border-collapse">
                <thead>
                   <tr className="bg-gray-50">
                      <th className="p-4 font-black uppercase tracking-widest text-gray-500 border-b border-gray-200">General (MFN)</th>
                      <th className="p-4 font-black uppercase tracking-widest text-gray-500 border-b border-gray-200">Special (FTAs)</th>
                      <th className="p-4 font-black uppercase tracking-widest text-gray-500 border-b border-gray-200">Column 2 (Embargo)</th>
                   </tr>
                </thead>
                <tbody>
                   <tr>
                      <td className="p-4 font-bold text-gray-900 align-top">{data.dutyInfo.general}</td>
                      <td className="p-4 text-gray-600 align-top">{data.dutyInfo.special}</td>
                      <td className="p-4 text-gray-600 align-top">{data.dutyInfo.column2}</td>
                   </tr>
                </tbody>
              </table>
           </div>
        </section>

        {/* Compliance Surcharges & Flags */}
        <div className="grid grid-cols-2 gap-8 break-inside-avoid">
           <section>
              <h4 className="text-[10px] font-black uppercase tracking-[0.2em] text-red-500 mb-3 border-b border-red-100 pb-1">Additional Tariffs</h4>
              <div className="bg-red-50 p-4 rounded-xl border border-red-100">
                 <p className="text-xs text-red-800 leading-relaxed font-medium whitespace-pre-wrap">{data.tariffInfo}</p>
              </div>
           </section>
           <section>
              <h4 className="text-[10px] font-black uppercase tracking-[0.2em] text-orange-500 mb-3 border-b border-orange-100 pb-1">Compliance Flags</h4>
              <div className="bg-orange-50 p-4 rounded-xl border border-orange-100">
                 <p className="text-xs text-orange-800 leading-relaxed font-medium whitespace-pre-wrap">{data.complianceInfo}</p>
              </div>
           </section>
        </div>

        {/* Disclaimer */}
        <section className="bg-zinc-50 p-6 rounded-2xl border border-zinc-100 break-inside-avoid">
            <h4 className="text-[10px] font-black uppercase tracking-widest text-zinc-400 mb-2">Legal Disclaimer</h4>
            <p className="text-[10px] text-zinc-500 leading-relaxed">
              This report is generated by an artificial intelligence assistant specializing in trade compliance. While the AI targets maximum accuracy based on official U.S. government datasets (HTSUS 2025 and CBP Rulings), this classification does not constitute legal advice. HTS classification is a complex legal process subject to interpretation by U.S. Customs and Border Protection. The importer of record maintains final legal responsibility for the accuracy of entry declarations. Consultation with a licensed Customs Broker or legal counsel is strongly advised for definitive classification.
            </p>
        </section>
      </main>

      <footer className="mt-12 pt-8 border-t border-gray-100 flex justify-between items-center text-[10px] font-bold text-gray-400 uppercase tracking-widest">
        <span>© {new Date().getFullYear()} TEU GLOBAL - AI DIVISION</span>
        <span>PAGE 1 OF 1</span>
        <span>CONFIDENTIAL COMPLIANCE DOCUMENT</span>
      </footer>
    </div>
  );
};

export default PrintableResult;
